---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: phonedepot-cluster
  region: us-east-1
  version: "1.25"

vpc:
  clusterEndpoints:
    publicAccess:  true
    privateAccess: true

nodeGroups:
  - name: ng-phonedepot
    instanceType: t3.medium
    desiredCapacity: 2